#ifndef PLAYERBOTS_SPECSTATEXPERIENCE_H
#define PLAYERBOTS_SPECSTATEXPERIENCE_H

#include <array>
#include <cstdint>

#include "StatsCollector.h"

namespace BotPlayerbotsGear
{
enum class GearExperience : uint8
{
    Safety = 0,
    Reliability,
    Volatility,
    Tempo,
    SelfSufficiency
};

struct SpecStatMembership
{
    uint8 playerClass;
    uint8 tab;
    bool tankVariant;
    uint8 stat;
    GearExperience exp;
    float membership;
};

constexpr std::array<SpecStatMembership, 388> SpecStatExperience = {{
    // Tanks. Stats absent for a spec are deliberate: no experience weight.
    {1, 2, true, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {1, 2, true, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.35f},
    {1, 2, true, STATS_TYPE_EXPERTISE, GearExperience::Safety, 0.2f},
    {1, 2, true, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {1, 2, true, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {1, 2, true, STATS_TYPE_STRENGTH, GearExperience::Safety, 0.25f},
    {1, 2, true, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {1, 2, true, STATS_TYPE_ARMOR, GearExperience::Safety, 0.35f},
    {1, 2, true, STATS_TYPE_ARMOR, GearExperience::Reliability, 0.2f},
    {1, 2, true, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.35f},
    {1, 2, true, STATS_TYPE_DEFENSE, GearExperience::Volatility, 0.2f},
    {1, 2, true, STATS_TYPE_DODGE, GearExperience::Safety, 0.35f},
    {1, 2, true, STATS_TYPE_DODGE, GearExperience::Volatility, 0.2f},
    {1, 2, true, STATS_TYPE_PARRY, GearExperience::Safety, 0.35f},
    {1, 2, true, STATS_TYPE_PARRY, GearExperience::Volatility, 0.2f},
    {1, 2, true, STATS_TYPE_BLOCK_RATING, GearExperience::Safety, 0.35f},
    {1, 2, true, STATS_TYPE_BLOCK_RATING, GearExperience::Reliability, 0.2f},
    {1, 2, true, STATS_TYPE_BLOCK_VALUE, GearExperience::Safety, 0.35f},
    {1, 2, true, STATS_TYPE_BLOCK_VALUE, GearExperience::Reliability, 0.2f},
    {2, 1, true, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {2, 1, true, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.35f},
    {2, 1, true, STATS_TYPE_EXPERTISE, GearExperience::Safety, 0.2f},
    {2, 1, true, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {2, 1, true, STATS_TYPE_HASTE, GearExperience::Tempo, 0.25f},
    {2, 1, true, STATS_TYPE_STRENGTH, GearExperience::Safety, 0.25f},
    {2, 1, true, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {2, 1, true, STATS_TYPE_ARMOR, GearExperience::Safety, 0.35f},
    {2, 1, true, STATS_TYPE_ARMOR, GearExperience::Reliability, 0.2f},
    {2, 1, true, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.3f},
    {2, 1, true, STATS_TYPE_DEFENSE, GearExperience::Volatility, 0.15f},
    {2, 1, true, STATS_TYPE_DEFENSE, GearExperience::Reliability, 0.1f},
    {2, 1, true, STATS_TYPE_DODGE, GearExperience::Safety, 0.35f},
    {2, 1, true, STATS_TYPE_DODGE, GearExperience::Volatility, 0.2f},
    {2, 1, true, STATS_TYPE_PARRY, GearExperience::Safety, 0.35f},
    {2, 1, true, STATS_TYPE_PARRY, GearExperience::Volatility, 0.2f},
    {2, 1, true, STATS_TYPE_BLOCK_RATING, GearExperience::Safety, 0.35f},
    {2, 1, true, STATS_TYPE_BLOCK_RATING, GearExperience::Reliability, 0.2f},
    {2, 1, true, STATS_TYPE_BLOCK_VALUE, GearExperience::Safety, 0.35f},
    {2, 1, true, STATS_TYPE_BLOCK_VALUE, GearExperience::Reliability, 0.2f},
    {2, 1, true, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.25f},
    {2, 1, true, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.125f},
    {6, 0, true, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {6, 0, true, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.35f},
    {6, 0, true, STATS_TYPE_EXPERTISE, GearExperience::Safety, 0.2f},
    {6, 0, true, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {6, 0, true, STATS_TYPE_HASTE, GearExperience::Tempo, 0.25f},
    {6, 0, true, STATS_TYPE_STRENGTH, GearExperience::Safety, 0.125f},
    {6, 0, true, STATS_TYPE_STAMINA, GearExperience::Safety, 0.35f},
    {6, 0, true, STATS_TYPE_STAMINA, GearExperience::SelfSufficiency, 0.2f},
    {6, 0, true, STATS_TYPE_ARMOR, GearExperience::Safety, 0.35f},
    {6, 0, true, STATS_TYPE_ARMOR, GearExperience::Reliability, 0.2f},
    {6, 0, true, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.35f},
    {6, 0, true, STATS_TYPE_DEFENSE, GearExperience::Volatility, 0.2f},
    {6, 0, true, STATS_TYPE_DODGE, GearExperience::Safety, 0.35f},
    {6, 0, true, STATS_TYPE_DODGE, GearExperience::Volatility, 0.2f},
    {6, 0, true, STATS_TYPE_PARRY, GearExperience::Safety, 0.35f},
    {6, 0, true, STATS_TYPE_PARRY, GearExperience::Volatility, 0.2f},
    {6, 1, true, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {6, 1, true, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.35f},
    {6, 1, true, STATS_TYPE_EXPERTISE, GearExperience::Safety, 0.2f},
    {6, 1, true, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {6, 1, true, STATS_TYPE_HASTE, GearExperience::Tempo, 0.25f},
    {6, 1, true, STATS_TYPE_STRENGTH, GearExperience::Safety, 0.125f},
    {6, 1, true, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {6, 1, true, STATS_TYPE_ARMOR, GearExperience::Safety, 0.35f},
    {6, 1, true, STATS_TYPE_ARMOR, GearExperience::Reliability, 0.2f},
    {6, 1, true, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.35f},
    {6, 1, true, STATS_TYPE_DEFENSE, GearExperience::Volatility, 0.2f},
    {6, 1, true, STATS_TYPE_DODGE, GearExperience::Safety, 0.35f},
    {6, 1, true, STATS_TYPE_DODGE, GearExperience::Volatility, 0.2f},
    {6, 1, true, STATS_TYPE_PARRY, GearExperience::Safety, 0.35f},
    {6, 1, true, STATS_TYPE_PARRY, GearExperience::Volatility, 0.2f},
    {6, 2, true, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {6, 2, true, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.35f},
    {6, 2, true, STATS_TYPE_EXPERTISE, GearExperience::Safety, 0.2f},
    {6, 2, true, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {6, 2, true, STATS_TYPE_HASTE, GearExperience::Tempo, 0.25f},
    {6, 2, true, STATS_TYPE_STRENGTH, GearExperience::Safety, 0.125f},
    {6, 2, true, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {6, 2, true, STATS_TYPE_ARMOR, GearExperience::Safety, 0.35f},
    {6, 2, true, STATS_TYPE_ARMOR, GearExperience::Reliability, 0.2f},
    {6, 2, true, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.35f},
    {6, 2, true, STATS_TYPE_DEFENSE, GearExperience::Volatility, 0.2f},
    {6, 2, true, STATS_TYPE_DODGE, GearExperience::Safety, 0.35f},
    {6, 2, true, STATS_TYPE_DODGE, GearExperience::Volatility, 0.2f},
    {6, 2, true, STATS_TYPE_PARRY, GearExperience::Safety, 0.35f},
    {6, 2, true, STATS_TYPE_PARRY, GearExperience::Volatility, 0.2f},
    {11, 1, true, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {11, 1, true, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.35f},
    {11, 1, true, STATS_TYPE_EXPERTISE, GearExperience::Safety, 0.2f},
    {11, 1, true, STATS_TYPE_CRIT, GearExperience::Volatility, 0.3f},
    {11, 1, true, STATS_TYPE_CRIT, GearExperience::Safety, 0.15f},
    {11, 1, true, STATS_TYPE_CRIT, GearExperience::SelfSufficiency, 0.1f},
    {11, 1, true, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {11, 1, true, STATS_TYPE_AGILITY, GearExperience::Safety, 0.175f},
    {11, 1, true, STATS_TYPE_AGILITY, GearExperience::Volatility, 0.1f},
    {11, 1, true, STATS_TYPE_STAMINA, GearExperience::Safety, 0.35f},
    {11, 1, true, STATS_TYPE_STAMINA, GearExperience::SelfSufficiency, 0.2f},
    {11, 1, true, STATS_TYPE_ARMOR, GearExperience::Safety, 0.35f},
    {11, 1, true, STATS_TYPE_ARMOR, GearExperience::Reliability, 0.2f},
    {11, 1, true, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.175f},
    {11, 1, true, STATS_TYPE_DEFENSE, GearExperience::Volatility, 0.1f},
    {11, 1, true, STATS_TYPE_DODGE, GearExperience::Safety, 0.35f},
    {11, 1, true, STATS_TYPE_DODGE, GearExperience::Volatility, 0.2f},
    {11, 1, true, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.125f},
    // Healers.
    {2, 0, false, STATS_TYPE_CRIT, GearExperience::SelfSufficiency, 0.3f},
    {2, 0, false, STATS_TYPE_CRIT, GearExperience::Tempo, 0.15f},
    {2, 0, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.1f},
    {2, 0, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.35f},
    {2, 0, false, STATS_TYPE_HASTE, GearExperience::Safety, 0.2f},
    {2, 0, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {2, 0, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {2, 0, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.35f},
    {2, 0, false, STATS_TYPE_MANA_REGENERATION, GearExperience::Reliability, 0.2f},
    {2, 0, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {2, 0, false, STATS_TYPE_INTELLECT, GearExperience::Safety, 0.1f},
    {5, 0, false, STATS_TYPE_CRIT, GearExperience::Safety, 0.3f},
    {5, 0, false, STATS_TYPE_CRIT, GearExperience::Reliability, 0.15f},
    {5, 0, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.1f},
    {5, 0, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.35f},
    {5, 0, false, STATS_TYPE_HASTE, GearExperience::Safety, 0.2f},
    {5, 0, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {5, 0, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {5, 0, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.5f},
    {5, 0, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.35f},
    {5, 0, false, STATS_TYPE_MANA_REGENERATION, GearExperience::Reliability, 0.2f},
    {5, 0, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {5, 0, false, STATS_TYPE_INTELLECT, GearExperience::Safety, 0.1f},
    {5, 1, false, STATS_TYPE_CRIT, GearExperience::SelfSufficiency, 0.3f},
    {5, 1, false, STATS_TYPE_CRIT, GearExperience::Tempo, 0.15f},
    {5, 1, false, STATS_TYPE_CRIT, GearExperience::Safety, 0.1f},
    {5, 1, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.35f},
    {5, 1, false, STATS_TYPE_HASTE, GearExperience::Safety, 0.2f},
    {5, 1, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {5, 1, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {5, 1, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.5f},
    {5, 1, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.35f},
    {5, 1, false, STATS_TYPE_MANA_REGENERATION, GearExperience::Reliability, 0.2f},
    {5, 1, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {5, 1, false, STATS_TYPE_INTELLECT, GearExperience::Safety, 0.1f},
    {11, 2, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.3f},
    {11, 2, false, STATS_TYPE_CRIT, GearExperience::Safety, 0.15f},
    {11, 2, false, STATS_TYPE_CRIT, GearExperience::Tempo, 0.1f},
    {11, 2, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.35f},
    {11, 2, false, STATS_TYPE_HASTE, GearExperience::Safety, 0.2f},
    {11, 2, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {11, 2, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {11, 2, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.5f},
    {11, 2, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.35f},
    {11, 2, false, STATS_TYPE_MANA_REGENERATION, GearExperience::Reliability, 0.2f},
    {11, 2, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {11, 2, false, STATS_TYPE_INTELLECT, GearExperience::Safety, 0.1f},
    {7, 2, false, STATS_TYPE_CRIT, GearExperience::SelfSufficiency, 0.3f},
    {7, 2, false, STATS_TYPE_CRIT, GearExperience::Safety, 0.15f},
    {7, 2, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.1f},
    {7, 2, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.35f},
    {7, 2, false, STATS_TYPE_HASTE, GearExperience::Safety, 0.2f},
    {7, 2, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {7, 2, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {7, 2, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.35f},
    {7, 2, false, STATS_TYPE_MANA_REGENERATION, GearExperience::Reliability, 0.2f},
    {7, 2, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {7, 2, false, STATS_TYPE_INTELLECT, GearExperience::Safety, 0.1f},
    // Melee DPS.
    {1, 0, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {1, 0, false, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.5f},
    {1, 0, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {1, 0, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {1, 0, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {1, 0, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {1, 1, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.35f},
    {1, 1, false, STATS_TYPE_HIT, GearExperience::Tempo, 0.2f},
    {1, 1, false, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.35f},
    {1, 1, false, STATS_TYPE_EXPERTISE, GearExperience::Tempo, 0.2f},
    {1, 1, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.35f},
    {1, 1, false, STATS_TYPE_CRIT, GearExperience::Tempo, 0.2f},
    {1, 1, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {1, 1, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {1, 1, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {2, 2, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {2, 2, false, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.5f},
    {2, 2, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.3f},
    {2, 2, false, STATS_TYPE_CRIT, GearExperience::Tempo, 0.15f},
    {2, 2, false, STATS_TYPE_CRIT, GearExperience::Safety, 0.1f},
    {2, 2, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.25f},
    {2, 2, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {2, 2, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {2, 2, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.5f},
    {2, 2, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.25f},
    {7, 1, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.35f},
    {7, 1, false, STATS_TYPE_HIT, GearExperience::Tempo, 0.2f},
    {7, 1, false, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.5f},
    {7, 1, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.3f},
    {7, 1, false, STATS_TYPE_CRIT, GearExperience::Tempo, 0.15f},
    {7, 1, false, STATS_TYPE_CRIT, GearExperience::SelfSufficiency, 0.1f},
    {7, 1, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {7, 1, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {7, 1, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {7, 1, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.25f},
    {7, 1, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.5f},
    {11, 1, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {11, 1, false, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.5f},
    {11, 1, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.35f},
    {11, 1, false, STATS_TYPE_CRIT, GearExperience::Tempo, 0.2f},
    {11, 1, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.25f},
    {11, 1, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {11, 1, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {11, 1, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.125f},
    {11, 1, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.25f},
    {11, 1, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.25f},
    {4, 0, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.35f},
    {4, 0, false, STATS_TYPE_HIT, GearExperience::Tempo, 0.2f},
    {4, 0, false, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.5f},
    {4, 0, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.35f},
    {4, 0, false, STATS_TYPE_CRIT, GearExperience::Tempo, 0.2f},
    {4, 0, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {4, 0, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {4, 0, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {4, 1, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.35f},
    {4, 1, false, STATS_TYPE_HIT, GearExperience::Tempo, 0.2f},
    {4, 1, false, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.5f},
    {4, 1, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {4, 1, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {4, 1, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {4, 1, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {4, 2, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {4, 2, false, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.5f},
    {4, 2, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.35f},
    {4, 2, false, STATS_TYPE_CRIT, GearExperience::Tempo, 0.1f},
    {4, 2, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {4, 2, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {6, 1, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {6, 1, false, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.5f},
    {6, 1, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {6, 1, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.35f},
    {6, 1, false, STATS_TYPE_HASTE, GearExperience::Volatility, 0.2f},
    {6, 1, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {6, 1, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {6, 2, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {6, 2, false, STATS_TYPE_EXPERTISE, GearExperience::Reliability, 0.5f},
    {6, 2, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {6, 2, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {6, 2, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {6, 2, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    // Ranged and casters.
    {3, 0, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {3, 0, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.35f},
    {3, 0, false, STATS_TYPE_CRIT, GearExperience::SelfSufficiency, 0.2f},
    {3, 0, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {3, 0, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {3, 0, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {3, 0, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {3, 0, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {3, 0, false, STATS_TYPE_PARRY, GearExperience::Safety, 0.25f},
    {3, 0, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.5f},
    {3, 0, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.25f},
    {3, 1, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {3, 1, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {3, 1, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {3, 1, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {3, 1, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {3, 1, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {3, 1, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {3, 1, false, STATS_TYPE_PARRY, GearExperience::Safety, 0.25f},
    {3, 1, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.5f},
    {3, 1, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.25f},
    {3, 2, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {3, 2, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.3f},
    {3, 2, false, STATS_TYPE_CRIT, GearExperience::Reliability, 0.15f},
    {3, 2, false, STATS_TYPE_CRIT, GearExperience::SelfSufficiency, 0.1f},
    {3, 2, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {3, 2, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {3, 2, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {3, 2, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {3, 2, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {3, 2, false, STATS_TYPE_PARRY, GearExperience::Safety, 0.25f},
    {3, 2, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.5f},
    {3, 2, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.25f},
    {8, 0, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {8, 0, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {8, 0, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {8, 0, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {8, 0, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {8, 0, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {8, 0, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {8, 0, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.5f},
    {8, 0, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.5f},
    {8, 0, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {8, 0, false, STATS_TYPE_INTELLECT, GearExperience::Volatility, 0.1f},
    {8, 1, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {8, 1, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {8, 1, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {8, 1, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {8, 1, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {8, 1, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {8, 1, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {8, 1, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.5f},
    {8, 1, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.5f},
    {8, 1, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {8, 1, false, STATS_TYPE_INTELLECT, GearExperience::Volatility, 0.1f},
    {8, 2, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {8, 2, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.35f},
    {8, 2, false, STATS_TYPE_CRIT, GearExperience::Reliability, 0.1f},
    {8, 2, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {8, 2, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {8, 2, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {8, 2, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {8, 2, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {8, 2, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.5f},
    {8, 2, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.5f},
    {8, 2, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {8, 2, false, STATS_TYPE_INTELLECT, GearExperience::Volatility, 0.1f},
    {9, 0, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {9, 0, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {9, 0, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {9, 0, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.35f},
    {9, 0, false, STATS_TYPE_STAMINA, GearExperience::SelfSufficiency, 0.1f},
    {9, 0, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {9, 0, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {9, 0, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {9, 0, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.5f},
    {9, 0, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.35f},
    {9, 0, false, STATS_TYPE_MANA_REGENERATION, GearExperience::Tempo, 0.2f},
    {9, 0, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {9, 0, false, STATS_TYPE_INTELLECT, GearExperience::Volatility, 0.1f},
    {9, 1, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {9, 1, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.35f},
    {9, 1, false, STATS_TYPE_CRIT, GearExperience::Reliability, 0.2f},
    {9, 1, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {9, 1, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.35f},
    {9, 1, false, STATS_TYPE_STAMINA, GearExperience::SelfSufficiency, 0.1f},
    {9, 1, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {9, 1, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {9, 1, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {9, 1, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.5f},
    {9, 1, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.35f},
    {9, 1, false, STATS_TYPE_MANA_REGENERATION, GearExperience::Tempo, 0.2f},
    {9, 1, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.15f},
    {9, 1, false, STATS_TYPE_INTELLECT, GearExperience::Volatility, 0.075f},
    {9, 1, false, STATS_TYPE_INTELLECT, GearExperience::Reliability, 0.05f},
    {9, 2, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {9, 2, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.5f},
    {9, 2, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {9, 2, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.35f},
    {9, 2, false, STATS_TYPE_STAMINA, GearExperience::SelfSufficiency, 0.1f},
    {9, 2, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {9, 2, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {9, 2, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {9, 2, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.5f},
    {9, 2, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.35f},
    {9, 2, false, STATS_TYPE_MANA_REGENERATION, GearExperience::Tempo, 0.2f},
    {9, 2, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {9, 2, false, STATS_TYPE_INTELLECT, GearExperience::Volatility, 0.1f},
    {5, 2, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {5, 2, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.35f},
    {5, 2, false, STATS_TYPE_CRIT, GearExperience::SelfSufficiency, 0.2f},
    {5, 2, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {5, 2, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {5, 2, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {5, 2, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {5, 2, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {5, 2, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.5f},
    {5, 2, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.5f},
    {5, 2, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {5, 2, false, STATS_TYPE_INTELLECT, GearExperience::Volatility, 0.1f},
    {11, 0, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {11, 0, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.3f},
    {11, 0, false, STATS_TYPE_CRIT, GearExperience::Tempo, 0.15f},
    {11, 0, false, STATS_TYPE_CRIT, GearExperience::Reliability, 0.1f},
    {11, 0, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {11, 0, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {11, 0, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {11, 0, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {11, 0, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {11, 0, false, STATS_TYPE_SPIRIT, GearExperience::SelfSufficiency, 0.5f},
    {11, 0, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.5f},
    {11, 0, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {11, 0, false, STATS_TYPE_INTELLECT, GearExperience::Volatility, 0.1f},
    {7, 0, false, STATS_TYPE_HIT, GearExperience::Reliability, 0.5f},
    {7, 0, false, STATS_TYPE_CRIT, GearExperience::Volatility, 0.35f},
    {7, 0, false, STATS_TYPE_CRIT, GearExperience::SelfSufficiency, 0.2f},
    {7, 0, false, STATS_TYPE_HASTE, GearExperience::Tempo, 0.5f},
    {7, 0, false, STATS_TYPE_STAMINA, GearExperience::Safety, 0.5f},
    {7, 0, false, STATS_TYPE_ARMOR, GearExperience::Safety, 0.5f},
    {7, 0, false, STATS_TYPE_DEFENSE, GearExperience::Safety, 0.25f},
    {7, 0, false, STATS_TYPE_DODGE, GearExperience::Safety, 0.25f},
    {7, 0, false, STATS_TYPE_BLOCK_RATING, GearExperience::Safety, 0.25f},
    {7, 0, false, STATS_TYPE_MANA_REGENERATION, GearExperience::SelfSufficiency, 0.5f},
    {7, 0, false, STATS_TYPE_INTELLECT, GearExperience::SelfSufficiency, 0.175f},
    {7, 0, false, STATS_TYPE_INTELLECT, GearExperience::Volatility, 0.1f},
}};

constexpr std::array<float, 5> GetStatExperience(uint8 playerClass, uint8 tab, bool tankVariant, uint8 stat)
{
    std::array<float, 5> memberships{};
    for (SpecStatMembership const& entry : SpecStatExperience)
    {
        if (entry.playerClass == playerClass && entry.tab == tab && entry.tankVariant == tankVariant &&
            entry.stat == stat)
        {
            memberships[static_cast<uint8>(entry.exp)] += entry.membership;
        }
    }
    return memberships;
}
}

#endif
